import logging
import os
import uuid
import httpx
from sqlalchemy.orm import Session
import models

logger = logging.getLogger(__name__)

YOOKASSA_API_URL = "https://api.yookassa.ru/v3/payments"

def get_yookassa_credentials():
    shop_id = os.getenv("YOOKASSA_SHOP_ID", "").strip()
    secret_key = os.getenv("YOOKASSA_SECRET_KEY", "").strip()
    return shop_id, secret_key

async def create_yookassa_payment(db: Session, user_id: int, amount_val: str = "990.00", return_url: str = None) -> str:
    """
    Creates a payment in YooKassa and saves a pending Payment in local DB.
    Returns the confirmation/checkout URL.
    """
    shop_id, secret_key = get_yookassa_credentials()
    
    if not shop_id or not secret_key:
        logger.warning("YooKassa credentials are not configured. Falling back to Mock Payment.")
        # If credentials are not set, we can simulate a mock payment for testing/dev environment
        mock_payment_id = f"mock_{uuid.uuid4()}"
        
        # Save mock payment to DB
        payment = models.Payment(
            yookassa_payment_id=mock_payment_id,
            user_id=user_id,
            amount=amount_val,
            status="pending"
        )
        db.add(payment)
        db.commit()
        
        # Return a simulated checkout URL pointing back to our referrals page but with a mock success parameter
        # to allow easy verification by clicking a mock complete button or auto-approving in mock mode.
        frontend_url = os.getenv("FRONTEND_URL", "http://localhost:8082").rstrip('/')
        return f"{frontend_url}/referrals?mock_payment_id={mock_payment_id}", mock_payment_id

    # Generate an idempotency key
    idempotency_key = str(uuid.uuid4())
    
    # We construct the final return URL to pass the payment ID back to the frontend on return
    # This enables instant client-side verification on return.
    if not return_url:
        frontend_url = os.getenv("FRONTEND_URL", "http://localhost:8082").rstrip('/')
        return_url = f"{frontend_url}/referrals"

    # We will append the payment_id to the return_url once we have the ID, or we can just let it redirect to return_url.
    # YooKassa doesn't allow dynamic placeholders in redirect, but we can generate a unique return_url per payment!
    # Let's append yookassa_payment_id as a query parameter in return_url.
    # To do that, we need the payment ID. Since we get the ID in the YooKassa response, we pass the return_url with a temporary query param or placeholder?
    # Wait, we can pass a unique return_url to the API for each payment. BUT we don't have the payment ID before we make the API request.
    # Ah! We can use our own system's internal ID, OR we can use the idempotency key!
    # Wait, the idempotency_key is a perfect identifier! Or we can use a custom transaction UUID generated by us!
    # Yes! A custom transaction UUID is perfect. Let's do that. We can append it to the return_url, and link it in the DB!
    # Wait, actually, YooKassa allows any return_url we provide in the request. If we use the idempotency key:
    # return_url = f"{frontend_url}/referrals?payment_id={idempotency_key}"
    # Wait, but YooKassa's payment ID is what is sent in the webhook, so using the actual yookassa payment ID is extremely nice.
    # Can we redirect the user to a route that handles the return and retrieves the payment ID?
    # Yes, or we can simply use the yookassa payment ID. Wait, if we use the idempotency key as the lookup key, we can easily lookup the payment!
    # Wait! In our Payment model, we have `yookassa_payment_id` which is the actual YooKassa ID.
    # We can also store the idempotency key, or just search by yookassa_payment_id.
    # Wait, if we use a unique ID (like our local payment ID or a custom uuid) and include that in return_url, e.g.:
    # return_url = f"{frontend_url}/referrals?payment_id={yookassa_id}"
    # Wait! Can we know the `yookassa_id` BEFORE we send the request? No.
    # BUT wait! Does YooKassa allow the return_url to contain the payment ID? No, because we have to supply return_url *inside* the request to create the payment!
    # So the return_url *cannot* contain the `yookassa_id` because the payment is not created yet when we define the return_url!
    # That is a brilliant realization!
    # So, how can the frontend know which payment was just made when returning?
    # 1. We can generate a local unique token or use a UUID for the payment (e.g. `transaction_id = str(uuid.uuid4())`), and save it to the `Payment` record in the database.
    # 2. We set `return_url = f"{frontend_url}/referrals?payment_id={transaction_id}"`.
    # 3. When the user returns, the frontend sends `payment_id` (which is our local `transaction_id`) to the backend `/api/payments/check/{payment_id}`.
    # 4. The backend looks up the `Payment` by `transaction_id` (or `yookassa_payment_id` if it matches).
    # This is incredibly clean, logical, and 100% correct! Let's do exactly this!
    # Let's add a `transaction_id` or just search by a custom UUID. Let's call it `payment_id` on the frontend and match it to a `local_id` / `idempotency_key` or `yookassa_payment_id` in our DB.
    # Actually, we can use the `yookassa_payment_id` directly for the mock flow, and for the real flow, we can use the `yookassa_payment_id` by saving the payment, getting the ID from the response, and then wait...
    # Wait! If the frontend initiates the payment, it *gets* the `yookassa_payment_id` in the response of `POST /api/payments/create`!
    # And the frontend can store it in `localStorage` or `zustand` store before redirecting the user!
    # Then, when the user returns, the frontend doesn't even need it in the URL query parameters! It can just read it from `localStorage` / `zustand` store!
    # Wow! That is extremely elegant, simple, requires zero extra columns, and works flawlessly!
    # Let's think: what if the user closes the tab or uses a different browser? If they do that, the webhook will still process the payment in the background, and when they open the site, they will have premium active! And if they return in the same session (99.9% of cases), we can check the status using the stored ID.
    # Wait, can we do BOTH? Yes! We can store the ID in the store/localStorage, AND we can also put a static query parameter like `?payment_check=true` in the return URL to tell the frontend to reload their profile and check if the subscription is active!
    # Yes! That is absolutely perfect! `return_url = f"{frontend_url}/referrals?payment_check=true"`.
    # When the frontend detects `?payment_check=true`, it calls `fetchMe()` to check if the user profile now has the premium subscription active. And if it has the payment ID in the store, it can also poll/check the status of that specific payment!
    # This is a magnificent design! Let's implement this!

    shop_id, secret_key = get_yookassa_credentials()
    
    if not shop_id or not secret_key:
        logger.warning("YooKassa credentials are not configured. Falling back to Mock Payment.")
        # If credentials are not set, we can simulate a mock payment for testing/dev environment
        mock_payment_id = f"mock_{uuid.uuid4()}"
        
        # Save mock payment to DB
        payment = models.Payment(
            yookassa_payment_id=mock_payment_id,
            user_id=user_id,
            amount=amount_val,
            status="pending"
        )
        db.add(payment)
        db.commit()
        
        frontend_url = os.getenv("FRONTEND_URL", "http://localhost:8082").rstrip('/')
        return f"{frontend_url}/referrals?mock_payment_id={mock_payment_id}"

    # Generate an idempotency key
    idempotency_key = str(uuid.uuid4())
    
    if not return_url:
        frontend_url = os.getenv("FRONTEND_URL", "http://localhost:8082").rstrip('/')
        return_url = f"{frontend_url}/referrals?payment_check=true"

    payload = {
        "amount": {
            "value": amount_val,
            "currency": "RUB"
        },
        "capture": True,
        "confirmation": {
            "type": "redirect",
            "return_url": return_url
        },
        "description": "Subscription for 30 days - reAnswer",
        "metadata": {
            "user_id": str(user_id)
        }
    }

    headers = {
        "Idempotence-Key": idempotency_key,
        "Content-Type": "application/json"
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(
                YOOKASSA_API_URL,
                json=payload,
                headers=headers,
                auth=(shop_id, secret_key),
                timeout=15.0
            )
            response.raise_for_status()
            data = response.json()
            
            yookassa_id = data.get("id")
            confirmation_url = data.get("confirmation", {}).get("confirmation_url")
            
            if not yookassa_id or not confirmation_url:
                raise ValueError("Invalid response structure from YooKassa")

            # Save payment to DB
            payment = models.Payment(
                yookassa_payment_id=yookassa_id,
                user_id=user_id,
                amount=amount_val,
                status="pending"
            )
            db.add(payment)
            db.commit()
            
            # Return both confirmation_url and payment_id so frontend can store the ID
            return confirmation_url, yookassa_id
        except Exception as e:
            logger.error(f"Failed to create YooKassa payment: {e}")
            raise

async def verify_and_process_payment(db: Session, yookassa_payment_id: str) -> bool:
    """
    Retrieves payment details from YooKassa, verifies it, and if succeeded, updates
    the user's subscription and updates the Payment status in DB.
    """
    payment = db.query(models.Payment).filter(models.Payment.yookassa_payment_id == yookassa_payment_id).first()
    if not payment:
        logger.warning(f"Payment {yookassa_payment_id} not found in database.")
        return False

    if payment.status == "succeeded":
        logger.info(f"Payment {yookassa_payment_id} was already processed successfully.")
        return True

    # If it's a mock payment (for dev testing)
    if yookassa_payment_id.startswith("mock_"):
        payment.status = "succeeded"
        # Update user subscription
        import crud
        crud.buy_full_subscription(db, user_id=payment.user_id)
        db.commit()
        logger.info(f"Mock Payment {yookassa_payment_id} processed successfully.")
        return True

    shop_id, secret_key = get_yookassa_credentials()
    if not shop_id or not secret_key:
        logger.error("YooKassa credentials are not configured but a real payment ID was requested.")
        return False

    async with httpx.AsyncClient() as client:
        try:
            url = f"{YOOKASSA_API_URL}/{yookassa_payment_id}"
            response = await client.get(
                url,
                auth=(shop_id, secret_key),
                timeout=15.0
            )
            response.raise_for_status()
            data = response.json()
            
            status = data.get("status")
            if status == "succeeded":
                payment.status = "succeeded"
                # Update user subscription
                import crud
                crud.buy_full_subscription(db, user_id=payment.user_id)
                db.commit()
                logger.info(f"YooKassa Payment {yookassa_payment_id} succeeded and user {payment.user_id} subscription extended.")
                return True
            elif status in ("canceled", "failed"):
                payment.status = "failed"
                db.commit()
                logger.info(f"YooKassa Payment {yookassa_payment_id} has failed/canceled status: {status}")
                return False
            else:
                logger.info(f"YooKassa Payment {yookassa_payment_id} is in status: {status}")
                return False
        except Exception as e:
            logger.error(f"Failed to verify YooKassa payment {yookassa_payment_id}: {e}")
            return False
